### ISSUE TITLE
Could not invoke PromptBluetoothReact.prompt

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#242] opened 2016-09-15 13:02 UTC
```
Could not invoke PromptBluetoothReact.prompt
```

**Comment by isabelrios** [comment] 2016-10-10 09:56
Think this is the same issue seen in #200 

Coping part of the logs: 
D/org.mozilla.magnet.MainActivity(30593): on pause
D/org.mozilla.magnet.MainActivity(30593): set active: false
I/ReactNativeJS(30593): '[App] app state changed', 'background'
I/ReactNativeJS(30593): [App] start scanning
E/AndroidRuntime(30593): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime(30593): Process: org.mozilla.magnet, PID: 30593
E/AndroidRuntime(30593): java.lang.RuntimeException: **Could not invoke PromptBluetoothReact.prompt**
E/AndroidRuntime(30593): at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:329)
E/AndroidRuntime(30593): at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:187)

Lets keep this open and will close the other one

**Comment by wilsonpage** [comment] 2016-10-13 13:58
@isabelrios can you confirm this is still apparent in latest builds. What are STR?

**Comment by isabelrios** [comment] 2016-10-14 13:10
When I was able to reproduce these were the steps:
-Launch magnet app and set it to background
-Pull down utility tray and disable bluetooth
-Set magnet to foreground
Most of the times the app crashed. 
But following these steps or other cannot reproduce this crash at least so far with latest builds. Closing the issue and in case I can reproduce again, will reopen it.

**Closed as completed by isabelrios** 2016-10-14 13:10 UTC
Labels: android, crash

**Comment by wilsonpage** [comment] 2016-10-14 14:06
Good news! \o/
