### ISSUE TITLE
Travis builds failing: 'Invalid user name'

### ISSUE THREAD

**Issue by wilsonpage** [mozilla-magnet/magnet-client#73] opened 2016-05-11 08:19 UTC
`https://:@ci.tengam.org/keystore/magnet-release.keystore: Invalid user name.`

https://travis-ci.org/mozilla-magnet/magnet-client/builds/129282331

**Comment by samgiles** [comment] 2016-05-12 14:22
Won't fix.  This fails by design, thankfully - and I remembered why in a dream, which was a weird one involving AWS :( ...

If you make a pull request to a repository that makes use of private variables on travis, you _could_ conceivably expose those with your changes creating a leak.  So, to prevent unknown people getting access to your private variables, you can only build on Travis if you push to the owning repository.  If you'd have pushed to magnet-client, this would've been fine.

**Closed as completed by samgiles** 2016-05-12 14:22 UTC

**Comment by wilsonpage** [comment] 2016-05-12 14:25
@samgiles but doesn't this mean that every build will fail on PR, meaning we can't get unit-test results?

**Comment by samgiles** [comment] 2016-05-12 14:49
Yes, as it stands.  Unless you push to this repository and make the PR from that branch,

**Comment by wilsonpage** [comment] 2016-05-12 16:21
I'm cool with that, just as long as it's a short-term issue. We shouldn't require every potential contributor to have push rights.
