### ISSUE TITLE
Scanning only adds new tiles but do not remove the ones that are not already in range

### ISSUE THREAD

**Issue by isabelrios** [mozilla-magnet/magnet-client#191] opened 2016-07-15 14:19 UTC
This is not new but how the app behaves. The thing is that with the notifications is more obvious and confusing because imagine you receive a notification with 1 item around and opening the app shows you a long list with previous availables tiles.

If you close the app or force a refresh then the list is correclty updated

**Comment by wilsonpage** [comment] 2016-07-18 09:05
Duplicate of #3

**Closed as completed by wilsonpage** 2016-07-18 09:05 UTC
Labels: android, ios
